### ISSUE TITLE
Improve adaptive cards layout

### ISSUE THREAD

**Issue by ROBROICH** [ROBROICH/TEAMS-Chatbot-Microsoft-SAP-Graph#10]
Currently the hero adaptive card is used to display data from the Microsoft- and SAP-Graph. 
For example to Outlook and SAP icons are to large. 

ToDo: Improve the adaptive card layout

Adaptive Cards sample are available here:
https://adaptivecards.io/samples/

**Comment by knaubw** [comment]
Hello Roman, i'd like to grab this issue

**Comment by knaubw** [comment]
Hello Roman,

i've implemented adaptive Cards in Merge Request #13 

Thanks and Regards
Walter

**Comment by ROBROICH** [comment]
Adaptive card looks great!
