### ISSUE TITLE
Handling of .env File

### ISSUE THREAD

**Issue by lechnerc77** [ROBROICH/TEAMS-Chatbot-Microsoft-SAP-Graph#6]
The repository contains a .env file that is used in the lab for local testing by putting in several credentials. The file might be pushed to a repository as it is not ignored during a git push. Consequently, the credential might become public

This should be corrected via the exclusion in .gitignore and creation of a template that serves as basis for the .env file and can be pushed in a repository

**Comment by ROBROICH** [comment]
Fixed by pull request, thank you!
