### ISSUE TITLE
Improvement of README File

### ISSUE THREAD

**Issue by lechnerc77** [ROBROICH/TEAMS-Chatbot-Microsoft-SAP-Graph#8]
The README.md file has room for two improvements:

- During the npm install node-gyp rebuild is executed. If Phython is not installed this step will fail. Hence, this should be mentioned in the prerequisites for the installation

- As the bot is running locally via NGROK it is worth to mention that restarting NGROK will make it necessary to adopt the Bot settings

**Comment by ROBROICH** [comment]
Updated per pull request, Thanks!
